incident_system_django/incident/urls.py
from django.urls import path, include

from rest_framework import routers

# from .view import reports_sla
from .views.reports_sla import (SlaComponentView,
                                SlaComponentDetailView,
                                SlaComponentQuartView,
                                SlaServiceView,
                                SlaServiceQuartView)

from .views.reports import (ReportSystemView,
                            ReportServiceView)

from .views.reports_problem import (ProblemView,
                                    ProblemDetailView)

from .views.job_calendar import (JobCalendarView,
                                 JobCalendarDetailView)

from .views.reports_notification import (NotificationCalendarView,
                                         NotificationCalendarDetailView,
                                         NotificationSendedView,
                                         NotificationSendedDetailView)

from .views.incident import (IncidentSimpleView,
                             IncidentDetailView,
                             IncidentFilterComponentOptionsListView,
                             IncidentFilterCategoryOptionsListView,
                             IncidentFilterListView,
                             IndexView)

from .views.answer import AnswerView
from .views.notification import NotificationCreateView
from .views.direction import DirectionCatalogView
from .views.system import SystemCatalogView
from .views.about import AboutView

from .views.export import ExportSystemsView
router = routers.DefaultRouter()

urlpatterns = [
    path('', IndexView.as_view()),
    path("<int:pk>", IncidentDetailView.as_view(), name='incident_view'),
    path("incident_simple/", IncidentSimpleView.as_view()),
    path("about/", AboutView.as_view(), name='about_url'),
    path("service_catalog/", DirectionCatalogView.as_view()),
    path("service_catalog/<int:pk>/", DirectionCatalogView.as_view()),
    path("system_catalog/", SystemCatalogView.as_view()),
    path("system_catalog/<int:pk>/", SystemCatalogView.as_view()),
    path("incident/<int:incident_id>/notification/create/",
         NotificationCreateView.as_view(),
         name='notification_create'),
    path("export_system",
         ExportSystemsView.as_view(),  name='export_systems_csv'),

    # SLA REPORTS #

    path("sla_component/",
         SlaComponentView.as_view(),
         {'external_problem': True},
         name='sla_component'),

    path("sla_component_without_external/",
         SlaComponentView.as_view(),
         {'external_problem': False},
         name='sla_component_without_external'),

    path("sla_component_detail/ \
         <int:year>/ \
         <int:quart>/ \
         <int:month>/ \
         <int:component>/ \
         <int:external_problem>",
         SlaComponentDetailView.as_view(), name='sla_component_detail'),

    path("sla_component_quart/",
         SlaComponentQuartView.as_view(), {'external_problem': True}),

    path("sla_component_quart_without_external/",
         SlaComponentQuartView.as_view(), {'external_problem': False}),

    path("sla_service/",
         SlaServiceView.as_view()),

    path("sla_service_quart/",
         SlaServiceQuartView.as_view()),

    path("reports_system/",
         ReportSystemView.as_view(),
         name='reports_system'),


    path("reports_service/",
         ReportServiceView.as_view()),

    path("answers/",
         AnswerView.as_view()),

    path("notification_calendar/",
         NotificationCalendarView.as_view()),

    path("notification_sended/",
         NotificationSendedView.as_view(),
         name='notification_sended'),

    path("notification_sended_detail/<int:pk>/",
         NotificationSendedDetailView.as_view(),
         name='notification_sended_detail'),

    path("notification_calendar/",
         NotificationCalendarView.as_view(),
         name='notification_calendar'),

    path("notification_calendar_detail/<int:pk>/",
         NotificationCalendarDetailView.as_view(),
         name='notification_calendar_detail'),

    path("job_calendar/",
         JobCalendarView.as_view(),
         name='job_calendar'),

    path("job_calendar_detail/<int:pk>",
         JobCalendarDetailView.as_view(),
         name='job_calendar_detail'),


    path("reports_problem/",
         ProblemView.as_view(),
         name='reports_problem'),

    path("reports_problem_detail/<int:pk>",
         ProblemDetailView.as_view(),
         name='reports_problem_detail'),


    # DATATABLES #

    path('api/', include(router.urls)),

    path(
        'api/filter/incidents/component/options/',
        IncidentFilterComponentOptionsListView.as_view(),
        name='incidents_filter_component_options_list'
    ),

    path(
        'api/filter/incidents/category/options/',
        IncidentFilterCategoryOptionsListView.as_view(),
        name='incidents_filter_category_options_list'
    ),

    path(
        'api/filter/incidents/',
        IncidentFilterListView.as_view(),
        name='incidents_filter_list'
    ),
]

incident_system_django/incident_system_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path("", include("incident.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

incident_system_django/incident/models/incident.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib import admin
from django.contrib.auth.models import User
# Create your models here.
from .profile import Employee


def get_first_name(self):
    return f"{self.first_name} {self.last_name}"


User.add_to_class("__str__", get_first_name)


class Direction(models.Model):
    name = models.CharField(max_length=50,
                            help_text="Напровление",
                            verbose_name="Направление")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Направление'
        verbose_name_plural = 'Направления'


class Service(models.Model):
    name = models.CharField(max_length=50,
                            help_text="Название сервиса",
                            verbose_name="Сервис")
    direction = models.ForeignKey(Direction,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  blank=True,
                                  verbose_name="Направление")
    sla = models.DecimalField(max_digits=4,
                              decimal_places=2,
                              null=True,
                              blank=True,
                              verbose_name="SLA для сервиса")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Сервис'
        verbose_name_plural = 'Сервисы'


class Influence(models.Model):
    name = models.CharField(max_length=50,
                            help_text="Влияние на бизнес",
                            verbose_name="Влияние на бизнес")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Влияние на бизнес'
        verbose_name_plural = 'Влияния на бизнес'


class InternalSupport(models.Model):
    name = models.CharField(max_length=50,
                            null=True,
                            blank=True,
                            help_text="Название команды",
                            verbose_name="Название команды")
    description = models.TextField(null=True,
                                   blank=True,
                                   verbose_name="Информация о команде")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Команда внутренней эксплуатации'
        verbose_name_plural = 'Команда внутренней эксплуатации'


class ExternalSupport(models.Model):
    name = models.CharField(max_length=50,
                            null=True,
                            blank=True,
                            help_text="Название команды",
                            verbose_name="Название команды")
    description = models.TextField(null=True,
                                   blank=True,
                                   verbose_name="Информация о команде")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Команда внешней эксплуатации'
        verbose_name_plural = 'Команда внешней эксплуатации'


class InternalContact(models.Model):
    name = models.CharField(max_length=50,
                            null=True,
                            blank=True,
                            help_text="Название контакта",
                            verbose_name="Название контакта")
    description = models.TextField(null=True,
                                   blank=True,
                                   verbose_name="Информация о контакте")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Внутренний контакт'
        verbose_name_plural = 'Внутренние контакты'


class ExternalContact(models.Model):
    name = models.CharField(max_length=50,
                            null=True,
                            blank=True,
                            help_text="Название контакта",
                            verbose_name="Название контакта")
    description = models.TextField(null=True,
                                   blank=True,
                                   verbose_name="Информация о контакте")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Внешний  контакт'
        verbose_name_plural = 'Внешние  контакты'


class Component(models.Model):
    RESPONSIBLE = (('IN', 'Внутреннее'),
                   ('EX', 'Внешнее'),
                   ('CL', 'Заказчик'))
    name = models.CharField(max_length=50,
                            help_text="Название системы",
                            verbose_name="Системы")
    owner = models.ForeignKey(Employee,
                              on_delete=models.SET_NULL,
                              null=True,
                              blank=True,
                              default=None,
                              verbose_name="Менеджер системы",
                              related_name='components')
    service = models.ManyToManyField(Service,
                                     blank=True,
                                     verbose_name="Сервис",
                                     related_name='components')
    internal_support = models.ForeignKey(InternalSupport,
                                         on_delete=models.SET_NULL,
                                         null=True,
                                         blank=True,
                                         default=None,
                                         verbose_name="Команда внутренней эксплуатации",
                                         related_name='components')
    external_support = models.ForeignKey(ExternalSupport,
                                         on_delete=models.SET_NULL,
                                         null=True, blank=True,
                                         default=None,
                                         verbose_name="Команда внешней эксплуатации",
                                         related_name='components')
    internal_contact = models.ForeignKey(InternalContact,
                                         on_delete=models.SET_NULL,
                                         null=True,
                                         blank=True,
                                         default=None,
                                         verbose_name="Внутренние контакты",
                                         related_name='components')
    external_contact = models.ForeignKey(ExternalContact,
                                         on_delete=models.SET_NULL,
                                         null=True,
                                         blank=True,
                                         default=None,
                                         verbose_name="Внешние контакты",
                                         related_name='components')
    responsible = models.CharField(max_length=2,
                                   default=None,
                                   choices=RESPONSIBLE,
                                   verbose_name="Обслуживание")
    influence = models.ForeignKey(Influence,
                                  on_delete=models.SET_NULL,
                                  null=True,
                                  verbose_name="Влияние на бизнес")
    sla = models.DecimalField(max_digits=4,
                              decimal_places=2,
                              null=True,
                              blank=True,
                              verbose_name="SLA для системы")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Система'
        verbose_name_plural = 'Системы'
        ordering = ['name']


class Category(models.Model):
    name = models.CharField(max_length=50,
                            help_text="Категория инцидента",
                            verbose_name="Категория инцидента")
    sla = models.BooleanField(default=False,
                              verbose_name="Категория инцидента участвует в расчёте SLA")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория инцидента'
        verbose_name_plural = 'Категории инцидентов'


class Status(models.Model):
    name = models.TextField(max_length=50,
                            verbose_name="Статус")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class Workflow(models.Model):
    name = models.TextField(max_length=150,
                            blank=True,
                            null=True,
                            verbose_name="Название процесса")
    label = models.TextField(max_length=150,
                             verbose_name="Пояснение")
    status = models.ForeignKey(Status,
                               on_delete=models.SET_NULL,
                               null=True,
                               verbose_name="Статус",
                               related_name='statuses')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Процесс'
        verbose_name_plural = 'Процессы'


class Affected(models.Model):
    name = models.CharField(max_length=30,
                            blank=True,
                            null=True,
                            verbose_name="Количество затрагиваемых сотрудников")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Количество затрагиваемых сотрудников'
        verbose_name_plural = 'Количество затрагиваемых сотрудников'


class ProblemStatus(models.Model):
    name = models.CharField(verbose_name="Статус проблемы",
                            max_length=30,
                            blank=True,
                            null=True
                            )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статус проблемы'

incident_system_django/incident/views/about.py
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin


class AboutView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request,
                      "incident/about.html",
                      {'nbar': 'about'})

incident_system_django/incident/views/answer.py
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.answer import Answer


class AnswerView(LoginRequiredMixin, View):
    def get(self, request):
        # import pdb; pdb.set_trace()
        answers = Answer.objects.all().order_by('name')
        return render(
            request,
            "incident/answer.html",
            {"answers": answers,
             'nbar': 'answer'}
        )

incident_system_django/incident/views/direction.py
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models.incident import Component
from ..forms import ServiceForm


class DirectionCatalogView(LoginRequiredMixin, View):
    def get(self, request):
        form = ServiceForm(initial={'service': 0})
        return render(request,
                      "incident/service_catalog.html",
                      {"form": form, 'nbar': 'sla_component'})

    def post(self, request):
        form = ServiceForm(request.POST)
        if form.is_valid():
            service_selected = form.data['service']
            component_list = Component.objects.all().filter(service=service_selected)
            form = ServiceForm(request.POST or None)
            return render(request,
                          "incident/service_catalog.html",
                          {"form": form, "component_list": component_list,
                           'nbar': 'sla_component'})
        else:
            form = ServiceForm(initial={'service': 0})
            return render(request,
                          "incident/service_catalog.html",
                          {"form": form, 'nbar': 'sla_component'})

incident_system_django/incident/templates/job_calendar/job_calendar.html
{% extends  "base.html" %}

{% block title %}
Календарь работ
{% endblock %}

{% block main %}


<link href="https://unpkg.com/tabulator-tables@5.4.4/dist/css/tabulator.min.css" rel="stylesheet">
<link href="/static/incident/css/tabulator_bootstrap5.min.css" rel="stylesheet">
<script type="text/javascript" src=" https://cdn.jsdelivr.net/npm/luxon@3.3.0/build/global/luxon.min.js "></script>

<script type="text/javascript" src="https://unpkg.com/tabulator-tables@5.4.4/dist/js/tabulator.min.js"></script>


 <div id="example-table"></div>
 <div> <button id="select-row" class="dt-button">Посмотреть подробно</button> </div>




{% endblock %}


{% block extra_js %}
<script>


document.getElementById("select-row").addEventListener("click", function(){
    var selectedData = table.getSelectedData();
    console.log(selectedData[0].pk);
    console.log(selectedData);  
    window.location.href = '/job_calendar_detail/' +  selectedData[0].id;

});


var tabledata =  {{ incidents }};
var DateTime = luxon.DateTime;

var table = new Tabulator("#example-table", {
  height:205, // set height of table (in CSS or here), this enables the Virtual DOM and improves render speed dramatically (can be any valid css height value)
  data:tabledata, //assign data to table
  layout:"fitData",
  pagination:"true",
  paginationSize:10,
  paginationSizeSelector:[10, 25, 50],
  paginationCounter:"rows",
  height:"100%",
  selectable:1,
  // layout:"fitColumns", //fit columns to width of table (optional)
  locale:"en-us",
    langs:{
        "en-us":{
            "pagination":{
                "page_size":"Кол-во строк", //label for the page size select element
                "first":"Первая", //text for the first page button
                "first_title":"Первая", //tooltip text for the first page button
                "last":"Последня",
                "last_title":"Последня",
                "prev":"Предыдущая",
                "prev_title":"Предыдущая",
                "next":"Следующая",
                "next_title":"Следующая",
                "counter":{
			           	"showing": "Показано",
    				      "of": "из",
				          "rows": "строк",
				          "pages": "страниц",
			          },
            }
        },

    },
  columns:[ //Define Table Columns
    {title:"Номер работ", field:"id", hozAlign:"center", headerFilter:"number", headerFilterPlaceholder:"введите номер", headerFilterFunc:"="},
    {title:"Плановое время", field:"formatted_date",  headerFilter:"input", headerFilterFunc:"like"},
    {title:"Система", field:"component__name", headerFilter:"list", headerFilterParams:{autocomplete:true, valuesLookup:true, clearable:true}},
    {title:"Категоирия", field:"category__name",  headerFilter:"list", headerFilterParams:{autocomplete:true, valuesLookup:true, clearable:true}},
  ],
});

// //trigger an alert message when the row is clicked
// table.on("rowClick", function(e, row){ 
//  alert("Row " + row.getData().id + " Clicked!!!!");
// });

</script>
{% endblock %}

incident_system_django/incident/templates/job_calendar/job_calendar_detail.html
{% extends  "base.html" %}

{% block title %}
Плановая работв
{% endblock %}

{% block main %}

<br> 

<div class="card">
    <h5 class="card-header">Плановая работа № {{incident.id}}</h5>
    <div class="card-body">
      {% comment %} <h5 class="card-title">Special title treatment</h5> {% endcomment %}
      <p class="card-text"><b>Дата начала работ:</b> {{incident.start_date}} </p>
      <p class="card-text"><b>Дата окончания работ:</b> {{incident.end_date}}</p>
      <p class="card-text"><b>Продолжительность(мин.):</b> {{incident.duration}} </p>
      <p class="card-text"><b>Направление:</b> {{incident.component.service.direction}}</p>
      <p class="card-text"><b>Компонент:</b> {{incident.component}}</p>
      <p class="card-text"><b>Обслуживание компонента:</b> {{incident.component.get_responsible_display}}</p>
      <p class="card-text"><b>Владалец компоненты сервиса:</b> {{incident.component.owner}}</p>
      <p class="card-text"><b>Категория работ:</b> {{incident.category}}</p>
      <p class="card-text"><b>Ссылка на задачу:</b> <a href={{incident.url}} target="_blank">{{incident.url}}</a></p>
      <p class="card-text"><b>Описание аварии:</b> {{incident.description}}</p>
      <p class="card-text"><b>Ответственный сотрудник:</b> {{incident.employee}}</p>
      <p class="card-text"><b>Причины работ:</b> {{incident.cause}}</p>
      <p class="card-text"><b>Проведенные мероприятия и рекомендации по устранению причин аварии:</b> {{incident.prevention}}</p>
      <p class="card-text"><b>Информирование руководства:</b> {{ incident.informimng|yesno:"Произведено,Не произведено" }}</p>
      <p class="card-text"><b>Учет при расчете SLA:</b> {{incident.sla|yesno:"Учитывается,Не учитывается"}}</p>
      <p class="card-text"><b>Сервисы:</b> {% for service in incident.component.service.all %}  {{service.name}}, {% endfor %}</p>
    </div>
  </div>




{% endblock %}


{% block extra_js %}



{% endblock %}